name: ecommerce
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
     #- uses: actions/checkout@v2
     - uses: actions/checkout@v4
     - uses: actions/setup-node@v4
       with:
        node-version: 14

     - name: Install dependencies
       run: npm ci
     - name: build 
       run: npm run build --if-present
     - name: test app
       run: npm test



    
