name: ecommerce
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2
     - working-directory: ./frontend
     - name: Install dependencies
       run: npm install
     - name: build 
       run: npm run build
     - name: test app
       run: npm test



    
