name: ecommerce
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
     - uses: actions/checkout@v2
       with:
          repository: seyi007i/ecommerce-store
          path: ./
          Sparse-checkout: frontend
          sparse-checkout-cone-mode: false
          #token: ${{ secrets.PAT_REPO_TOKEN }} ```
     
     - name: Install dependencies
       run: npm install
     - name: build 
       run: npm run build
     - name: test app
       run: npm test



    
